### ISSUE TITLE
Use pymongo to insert data, show error "pymongo.errors.BulkWriteError: batch op errors occurred"

### ISSUE THREAD

**Issue by Quesle** [flyingSprite/spinelle#5]
For crawling aliyun data every hour, assure not lose data, should update more than one hour data.
But when insert data, have this issue:

```
Traceback (most recent call last):
  File "spinelle/run.py", line 65, in <module>
    service.start_aliyun_cms()
  File "spinelle/run.py", line 52, in start_aliyun_cms
    run()
  File "/Users/Fernando/Develop/solutions/spinelle/service/aliyun_cms.py", line 35, in run
    request_id=request_id
  File "/Users/Fernando/Develop/solutions/spinelle/service/aliyun_cms.py", line 65, in parse_cpu_utilization
    self.save(items)
  File "/Users/Fernando/Develop/solutions/spinelle/service/aliyun_cms.py", line 70, in save
    self.collection.insert_many(items)
  File "/usr/local/lib/python2.7/site-packages/pymongo/collection.py", line 684, in insert_many
    blk.execute(self.write_concern.document)
  File "/usr/local/lib/python2.7/site-packages/pymongo/bulk.py", line 470, in execute
    return self.execute_command(sock_info, generator, write_concern)
  File "/usr/local/lib/python2.7/site-packages/pymongo/bulk.py", line 314, in execute_command
    raise BulkWriteError(full_result)
pymongo.errors.BulkWriteError: batch op errors occurred
```

**Comment by Quesle** [comment]
When the primary key has existed, show be show this issue

**Comment by Siva-Karthi** [comment]
Try this https://stackoverflow.com/questions/30355790/mongodb-bulk-write-error
